---
- name: Install centos-release-gluster package
  yum:
    name: centos-release-gluster312
    state: present


- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"

- name: Enable glusterd service
  systemd:
    name: glusterd
    state: started
    enabled: yes
