---
- name: Install required packages
  yum:
    name: NetworkManager
    state: present

- name: Enable NetworkManager service
  systemd:
    name: NetworkManager
    state: started
    enabled: yes
